name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar Node
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Instalando dependências
        run: npm install

      - name: Rodar build
        run: npm run build

      - name: Testes unitários
        run: npm run test
